repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: autopep8
        name: autopep8
        entry: autopep8 --in-place --aggressive --aggressive
        language: python
        types: [python]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: commitizen-check
        name: Commitizen check commit message
        entry: cz check --commit-msg-file
        language: python
        additional_dependencies: ["commitizen"]
        stages: [commit-msg]
