[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"

[tool.commitizen.customize]
schema = "<type>- <subject>"
schema_pattern = "^(feat|fix|docs|test|build|perf|style|refactor|chore|ci|raw|cleanup|remove): .+"
bump_pattern = "^(feat|fix|perf|refactor)"
bump_map = {feat = "minor", fix = "patch", perf = "patch", refactor = "patch"}

[tool.commitizen.customize.types]
feat = "Commit adding a new feature"
fix = "Commit fixing a bug"
docs = "Commit changing documentation"
test = "Commit changing or adding tests"
build = "Commit related to build or dependencies"
perf = "Commit related to performance"
style = "Commit for code style, no functional changes"
refactor = "Commit refactoring without changing functionality"
chore = "Commit for administrative tasks or maintenance"
ci = "Commit related to continuous integration"
raw = "Commit changing configuration/data files"
cleanup = "Commit cleaning unnecessary code"
remove = "Commit removing obsolete files or functions"
